namespace Script {
  export type Data = { german: string, meenzer: string, img: Request };

  export let data: Data[] = [
    { meenzer: "Babbel!", german: "Sprich! Rede!", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Aach", german: "Auge", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Aachedeckel", german: "Augenlid", img: new Request("./Img/Questionmark.png") },
    { meenzer: "aarisch", german: "sehr", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Äbbel", german: "Äpfel", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Abbelkrotze", german: "Kerngehäuse vom Apfel", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Adschee", german: "Adieu", img: new Request("./Img/Questionmark.png") },
    { meenzer: "ald Scheckel", german: "alte Frau", img: new Request("./Img/Questionmark.png") },
    { meenzer: "alleweil", german: "jetzt sofort", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Atzel", german: "Perücke", img: new Request("./Img/Questionmark.png") },
    { meenzer: "babbisch Gutzje", german: "schmutzige Frau oder Kind", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Batschel", german: "ungeschickter Mensch", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Batschkabb", german: "Schirmmütze", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Berzel", german: "	Kopf", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Blummescherb", german: "Blumentopf aus Ton", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Blunz", german: "Blutwurst", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Bobbelche", german: "Säugling", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Bobbes", german: "Gesäß", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Bollesje", german: "Gefängnis", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Bombo", german: "Bonbon", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Borzel", german: "kleines Kind", img: new Request("./Img/Questionmark.png") },
    { meenzer: "bossele", german: "basteln", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Brockelscher", german: "Rosenkohl", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Butze", german: "Polizist", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Butzebebel", german: "Nasenpopel", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Dibbsche", german: "kleiner Topf", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Dibbe", german: "Topf", img: new Request("./Img/Questionmark.png") },
    { meenzer: "dick Blunz", german: "Schimpfwort für eine dicke Frau", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Dierschlink", german: "Türklinke", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Dorscht", german: "Durst", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Dubbee", german: "Toupet", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Dutt", german: "Tüte", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Geil", german: "Pferde", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Geilskniddel", german: "Pferdeapfel", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Gemies", german: "Gemüse", img: new Request("./Img/Questionmark.png") },
    { meenzer: "gemoschderd", german: "unmögliche Kleiderkombination", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Gutzje", german: "Bonbon", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Haggele", german: "Kiefer- oder Tannenzapfen", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Haggesjer", german: "Milchzähne", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Herrgottsdierche", german: "Marienkäfer", img: new Request("./Img/Questionmark.png") },
    { meenzer: "ibberhibbelt", german: "übersprungen oder übergangen", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Kabb", german: "Mütze", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Kabottche", german: "unmoderner Hut", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Katzuff", german: "Metzger", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Kerb", german: "Kirchweihfest", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Kerch", german: "Kirche", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Kimmche", german: "große Tasse", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Kinnerschees", german: "Kinderwagen", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Knadscher", german: "Bäcker", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Knerzje", german: "Endstück vom Brot oder Braten", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Kniddel", german: "Tierkot", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Knolle", german: "polizeiliche Geldstrafe", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Kobberd", german: "Kopfsprung", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Krebbel", german: "Berliner bzw. Krapfen", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Krimmele", german: "Krümel", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Lomberie", german: "Bodenabschlussleiste an der Wand", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Lattwerch", german: "steif gekochtes Zwetschgenmus", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Liehbeidel", german: "Lügner", img: new Request("./Img/Questionmark.png") },
    { meenzer: "machulle", german: "bankrott", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Meggeldasch", german: "Einkaufstasche", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Mick", german: "Mücke", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Mickeblatsch", german: "Fliegenklatsche", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Mutsch", german: "Kosewort für Mutter", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Nuddelche", german: "Schnuller", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Nuddelfläschje", german: "Trinkflasche mit Sauger", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Oongstschisser", german: "ängstlicher Mensch", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Oonk", german: "Genick", img: new Request("./Img/Questionmark.png") },
    { meenzer: "oogeduddelt", german: "angetrunken", img: new Request("./Img/Questionmark.png") },
    { meenzer: "pischbern", german: "flüstern", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Prottsche", german: "polizeiliche Geldstrafe", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Quetsche", german: "Zwetschgen bzw. Pflaumen", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Rachebutzer", german: "saurer Wein", img: new Request("./Img/Questionmark.png") },
    { meenzer: "rack", german: "steif", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Reitschul", german: "Kinderkarussell", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Ribbelkuche", german: "Streuselkuchen", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Rotzfohn", german: "Taschentuch", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Rullo", german: "Jalousie", img: new Request("./Img/Questionmark.png") },
    { meenzer: "schebb", german: "schief und krumm", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Schelleklobbe", german: "klingeln und dann wegrennen", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Schinnos", german: "Luder", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Schlebbche", german: "Schleifchen", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Schlibber", german: "Holzsplitter in der Haut", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Schlickse", german: "Schluckauf", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Schlobb", german: "Schleife", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Schminzje", german: "zierliches Kind", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Schmiss", german: "Schläge", img: new Request("./Img/Questionmark.png") },
    { meenzer: "schneegelisch", german: "wählerisch beim Essen", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Schnorres", german: "Schnauzbart", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Schnut", german: "Mund", img: new Request("./Img/Questionmark.png") },
    { meenzer: "schnuddelisch", german: "unsauber", img: new Request("./Img/Questionmark.png") },
    { meenzer: "schnuckele", german: "naschen", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Schockelgaul", german: "Schaukelpferd", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Schrumbele", german: "Falten im Gesicht", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Säckel", german: "Tasche in Kleidungsstücken", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Spätzje", german: "Penis", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Stiftekopp", german: "kurz geschnittene Haare", img: new Request("./Img/Questionmark.png") },
    { meenzer: "strunzen", german: "angeben", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Strunzer", german: "Prahler", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Stumbe", german: "Zigarre", img: new Request("./Img/Questionmark.png") },
    { meenzer: "vebummbeidelt", german: "verschlampt", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Verdel", german: "achtel Liter Wein", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Verdelsbutze", german: "Polizist in einem Stadtteil", img: new Request("./Img/Questionmark.png") },
    { meenzer: "veklebbern", german: "verrühren", img: new Request("./Img/Questionmark.png") },
    { meenzer: "veklickern", german: "genau erklären", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Wombe", german: "dicker Bauch", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Welljerholz", german: "Nudelholz", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Worscht", german: "Wurst", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Worzelberscht", german: "Wurzelbürste", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Wutz", german: "Schwein", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Wutzebeehle", german: "schlampige Frau", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Zibbelsche", german: "Endstück der Wurst", img: new Request("./Img/Questionmark.png") },
    { meenzer: "zobbele", german: "zupfen", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Zores", german: "Gesindel", img: new Request("./Img/Questionmark.png") },
    { meenzer: "Zwerndobbsch", german: "kleines lebhaftes Kind", img: new Request("./Img/Questionmark.png") }
  ]
}