namespace Script {
  export let data: { german: string, meenzer: string, url: Request }[] = [
    { meenzer: "Babbel!", german: "Sprich! Rede!", url: new Request("./Img/Questionmark.png") }, 
    { meenzer: "Aach", german: "Auge", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Aachedeckel", german: "Augenlid", url: new Request("./Img/Questionmark.png") },
    { meenzer: "aarisch", german: "sehr", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Äbbel", german: "Äpfel", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Abbelkrotze", german: "Kerngehäuse vom Apfel", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Adschee", german: "Adieu", url: new Request("./Img/Questionmark.png") },
    { meenzer: "ald Scheckel", german: "alte Frau", url: new Request("./Img/Questionmark.png") },
    { meenzer: "alleweil", german: "jetzt sofort", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Atzel", german: "Perücke", url: new Request("./Img/Questionmark.png") },
    { meenzer: "babbisch Gutzje", german: "schmutzige Frau oder Kind", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Batschel", german: "ungeschickter Mensch", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Batschkabb", german: "Schirmmütze", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Berzel", german: "	Kopf", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Blummescherb", german: "Blumentopf aus Ton", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Blunz", german: "Blutwurst", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Bobbelche", german: "Säugling", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Bobbes", german: "Gesäß", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Bollesje", german: "Gefängnis", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Bombo", german: "Bonbon", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Borzel", german: "kleines Kind", url: new Request("./Img/Questionmark.png") },
    { meenzer: "bossele", german: "basteln", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Brockelscher", german: "Rosenkohl", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Butze", german: "Polizist", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Butzebebel", german: "Nasenpopel", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Dibbsche", german: "kleiner Topf", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Dibbe", german: "Topf", url: new Request("./Img/Questionmark.png") },
    { meenzer: "dick Blunz", german: "Schimpfwort für eine dicke Frau", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Dierschlink", german: "Türklinke", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Dorscht", german: "Durst", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Dubbee", german: "Toupet", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Dutt", german: "Tüte", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Geil", german: "Pferde", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Geilskniddel", german: "Pferdeapfel", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Gemies", german: "Gemüse", url: new Request("./Img/Questionmark.png") },
    { meenzer: "gemoschderd", german: "unmögliche Kleiderkombination", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Gutzje", german: "Bonbon", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Haggele", german: "Kiefer- oder Tannenzapfen", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Haggesjer", german: "Milchzähne", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Herrgottsdierche", german: "Marienkäfer", url: new Request("./Img/Questionmark.png") },
    { meenzer: "ibberhibbelt", german: "übersprungen oder übergangen", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Kabb", german: "Mütze", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Kabottche", german: "unmoderner Hut", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Katzuff", german: "Metzger", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Kerb", german: "Kirchweihfest", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Kerch", german: "Kirche", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Kimmche", german: "große Tasse", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Kinnerschees", german: "Kinderwagen", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Knadscher", german: "Bäcker", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Knerzje", german: "Endstück vom Brot oder Braten", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Kniddel", german: "Tierkot", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Knolle", german: "polizeiliche Geldstrafe", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Kobberd", german: "Kopfsprung", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Krebbel", german: "Berliner bzw. Krapfen", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Krimmele", german: "Krümel", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Lomberie", german: "Bodenabschlussleiste an der Wand", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Lattwerch", german: "steif gekochtes Zwetschgenmus", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Liehbeidel", german: "Lügner", url: new Request("./Img/Questionmark.png") },
    { meenzer: "machulle", german: "bankrott", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Meggeldasch", german: "Einkaufstasche", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Mick", german: "Mücke", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Mickeblatsch", german: "Fliegenklatsche", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Mutsch", german: "Kosewort für Mutter", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Nuddelche", german: "Schnuller", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Nuddelfläschje", german: "Trinkflasche mit Sauger", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Oongstschisser", german: "ängstlicher Mensch", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Oonk", german: "Genick", url: new Request("./Img/Questionmark.png") },
    { meenzer: "oogeduddelt", german: "angetrunken", url: new Request("./Img/Questionmark.png") },
    { meenzer: "pischbern", german: "flüstern", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Prottsche", german: "polizeiliche Geldstrafe", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Quetsche", german: "Zwetschgen bzw. Pflaumen", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Rachebutzer", german: "saurer Wein", url: new Request("./Img/Questionmark.png") },
    { meenzer: "rack", german: "steif", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Reitschul", german: "Kinderkarussell", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Ribbelkuche", german: "Streuselkuchen", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Rotzfohn", german: "Taschentuch", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Rullo", german: "Jalousie", url: new Request("./Img/Questionmark.png") },
    { meenzer: "schebb", german: "schief und krumm", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Schelleklobbe", german: "klingeln und dann wegrennen", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Schinnos", german: "Luder", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Schlebbche", german: "Schleifchen", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Schlibber", german: "Holzsplitter in der Haut", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Schlickse", german: "Schluckauf", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Schlobb", german: "Schleife", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Schminzje", german: "zierliches Kind", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Schmiss", german: "Schläge", url: new Request("./Img/Questionmark.png") },
    { meenzer: "schneegelisch", german: "wählerisch beim Essen", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Schnorres", german: "Schnauzbart", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Schnut", german: "Mund", url: new Request("./Img/Questionmark.png") },
    { meenzer: "schnuddelisch", german: "unsauber", url: new Request("./Img/Questionmark.png") },
    { meenzer: "schnuckele", german: "naschen", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Schockelgaul", german: "Schaukelpferd", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Schrumbele", german: "Falten im Gesicht", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Säckel", german: "Tasche in Kleidungsstücken", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Spätzje", german: "Penis", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Stiftekopp", german: "kurz geschnittene Haare", url: new Request("./Img/Questionmark.png") },
    { meenzer: "strunzen", german: "angeben", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Strunzer", german: "Prahler", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Stumbe", german: "Zigarre", url: new Request("./Img/Questionmark.png") },
    { meenzer: "vebummbeidelt", german: "verschlampt", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Verdel", german: "achtel Liter Wein", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Verdelsbutze", german: "Polizist in einem Stadtteil", url: new Request("./Img/Questionmark.png") },
    { meenzer: "veklebbern", german: "verrühren", url: new Request("./Img/Questionmark.png") },
    { meenzer: "veklickern", german: "genau erklären", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Wombe", german: "dicker Bauch", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Welljerholz", german: "Nudelholz", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Worscht", german: "Wurst", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Worzelberscht", german: "Wurzelbürste", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Wutz", german: "Schwein", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Wutzebeehle", german: "schlampige Frau", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Zibbelsche", german: "Endstück der Wurst", url: new Request("./Img/Questionmark.png") },
    { meenzer: "zobbele", german: "zupfen", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Zores", german: "Gesindel", url: new Request("./Img/Questionmark.png") },
    { meenzer: "Zwerndobbsch", german: "kleines lebhaftes Kind", url: new Request("./Img/Questionmark.png") }
  ]
}